[buildPlans.iosevka-pure]
family = "Iosevka Pure"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

  [buildPlans.iosevka-pure.variants]
  inherits = "ss14"

    [buildPlans.iosevka-pure.variants.design]
    capital-q = "crossing"
    y = "straight"
    eszet = "sulzbacher"
    lower-lambda = "straight"
    zero = "reverse-slashed"
    seven = "straight-serifless"
    eight = "two-circles"
    tilde = "low"
    asterisk = "penta-high"
    underscore = "high"
    paragraph-sign = "high"
    paren = "normal"
    brace = "straight"
    ampersand = "upper-open"
    bar = "natural-slope"
    question = "smooth"

    [buildPlans.iosevka-pure.variants.italic]
    a = "double-storey-serifless"
    f = "serifless"

    [buildPlans.iosevka-pure.variants.oblique]
    a = "double-storey-serifless"
    f = "serifless"

  [buildPlans.iosevka-pure.ligations]
  inherits = "dlig"

